// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

//go:embed Resources/Images/KrankyBearVikingHelmet.png
var resourceKrankyBearVikingHelmetPngData []byte
var resourceKrankyBearVikingHelmetPng = &fyne.StaticResource{
	StaticName:    "Resources/Images/KrankyBearVikingHelmet.png",
	StaticContent: resourceKrankyBearVikingHelmetPngData,
}

//go:embed Resources/Images/KrankyBearHardHat.png
var resourceKrankyBearHardHatPngData []byte
var resourceKrankyBearHardHatPng = &fyne.StaticResource{
	StaticName:    "Resources/Images/KrankyBearHardHat.png",
	StaticContent: resourceKrankyBearHardHatPngData,
}

//go:embed Resources/Sounds/boing.mp3
var resourceBoingMp3Data []byte
var resourceBoingMp3 = &fyne.StaticResource{
	StaticName:    "Resources/Sounds/boing.mp3",
	StaticContent: resourceBoingMp3Data,
}

//go:embed Resources/Sounds/KrankyBearGrowl.mp3
var resourceKrankyBearGrowlMp3Data []byte
var resourceKrankyBearGrowlMp3 = &fyne.StaticResource{
	StaticName:    "Resources/Sounds/KrankyBearGrowl.mp3",
	StaticContent: resourceKrankyBearGrowlMp3Data,
}

//go:embed Resources/Sounds/uhOh.mp3
var resourceUhOhMp3Data []byte
var resourceUhOhMp3 = &fyne.StaticResource{
	StaticName:    "Resources/Sounds/uhOh.mp3",
	StaticContent: resourceUhOhMp3Data,
}

//go:embed Resources/Sounds/wheeHoo.mp3
var resourceWheeHooMp3Data []byte
var resourceWheeHooMp3 = &fyne.StaticResource{
	StaticName:    "Resources/Sounds/wheeHoo.mp3",
	StaticContent: resourceWheeHooMp3Data,
}

//go:embed Resources/Sounds/zip.mp3
var resourceZipMp3Data []byte
var resourceZipMp3 = &fyne.StaticResource{
	StaticName:    "Resources/Sounds/zip.mp3",
	StaticContent: resourceZipMp3Data,
}

// "Now this is not the end. It is not even the beginning of the end. But it is, perhaps, the end of the beginning." Winston Churchill, November 10, 1942
