[Details]
ID = "com.github.amarillier.KrankyBearTetris"
Name = "KrankyBear Tetris"
Creator = "Allan Marillier"
Version = "0.1.0"
Build = 2
Icon = "KrankyBearVikingHelmet.png"

[Migrations]
  fyneDo = true

[Development]
  HelperText = "This binary was built with debug symbols"

[Release]
  HelperText = "This binary was built without debug symbols"